# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('brewer', models.CharField(max_length=100)),
                ('asst_brewer', models.CharField(max_length=100)),
                ('batch_size', models.DecimalField(decimal_places=4, max_digits=10)),
                ('boil_size', models.DecimalField(decimal_places=4, max_digits=10)),
                ('boil_time', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
