# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0002_auto_20170310_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='creator',
        ),
    ]
