# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0007_auto_20170313_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('default_alpha', models.DecimalField(decimal_places=4, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('form', models.CharField(blank=True, max_length=100)),
                ('default_beta', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('hsi', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('origin', models.TextField(blank=True)),
                ('substitutes', models.TextField(blank=True)),
                ('default_humulene', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('default_caryophyllene', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('default_cohumulone', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('default_myrcene', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hop_usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('alpha', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('use', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('beta', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('humulene', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('carophyllene', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('cohumulone', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('myrcene', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('hop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brewery.Hop')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='misc',
        ),
        migrations.AlterField(
            model_name='misc_usage',
            name='misc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brewery.Misc'),
        ),
        migrations.AlterField(
            model_name='misc_usage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miscs', to='brewery.Recipe'),
        ),
        migrations.AddField(
            model_name='hop_usage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hops', to='brewery.Recipe'),
        ),
    ]
