# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0008_auto_20170313_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
                ('labratory', models.CharField(blank=True, max_length=100)),
                ('product_id', models.CharField(blank=True, max_length=100)),
                ('min_temperature', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('max_temperature', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('flocculation', models.CharField(blank=True, max_length=100)),
                ('attenuation', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('best_for', models.TextField(blank=True)),
                ('max_reuse', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yeast_usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('amount_is_weight', models.BooleanField(default=False)),
                ('times_cultured', models.IntegerField(null=True)),
                ('add_to_secondary', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeasts', to='brewery.Recipe')),
                ('yeast', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brewery.Yeast')),
            ],
        ),
        migrations.AlterField(
            model_name='hop',
            name='form',
            field=models.CharField(max_length=100),
        ),
    ]
