# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0010_auto_20170313_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fermentable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('raw_yield', models.DecimalField(decimal_places=4, max_digits=10)),
                ('color', models.DecimalField(decimal_places=4, max_digits=10)),
                ('origin', models.TextField(blank=True)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('coarse_fine_diff', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('moisture', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('diastatic_power', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('protein', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('max_in_batch', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('recommend_mash', models.BooleanField(default=True)),
                ('ibu_gal_per_lb', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fermentable_usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('add_after_boil', models.BooleanField(default=False)),
                ('fermentable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brewery.Fermentable')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fermentables', to='brewery.Recipe')),
            ],
        ),
    ]
