# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0011_fermentable_fermentable_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('calcium', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bicarbonate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sulfate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('chloride', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sodium', models.DecimalField(decimal_places=4, max_digits=10)),
                ('magnesium', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ph', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Water_usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waters', to='brewery.Recipe')),
                ('water', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brewery.Water')),
            ],
        ),
    ]
