# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0013_auto_20170313_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('category_number', models.IntegerField()),
                ('style_letter', models.CharField(max_length=100)),
                ('style_guide', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('og_min', models.DecimalField(decimal_places=4, max_digits=10)),
                ('og_max', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fg_min', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fg_max', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ibu_min', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ibu_max', models.DecimalField(decimal_places=4, max_digits=10)),
                ('color_min', models.DecimalField(decimal_places=4, max_digits=10)),
                ('color_max', models.DecimalField(decimal_places=4, max_digits=10)),
                ('carb_min', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('carb_max', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('abv_min', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('abv_max', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('profile', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('examples', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brewery.Style'),
        ),
    ]
