# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0018_auto_20170313_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('manual_temp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('manual_heat_diff', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('manual_cool_diff', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('operation_type', models.CharField(default='Off', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fermenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fermenter', to='brewery.Chamber')),
            ],
        ),
        migrations.AddField(
            model_name='chamber',
            name='active_fermenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_fermenter', to='brewery.Fermenter'),
        ),
    ]
