# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0019_auto_20170313_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('manual_temp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('manual_heat_diff', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('manual_cool_diff', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('operation_type', models.CharField(default='Off', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('kegerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Taps', to='brewery.Kegerator')),
            ],
        ),
        migrations.AddField(
            model_name='fermenter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fermenter',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kegerator',
            name='active_tap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_tap', to='brewery.Fermenter'),
        ),
    ]
