# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0023_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='efficiency',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='est_abv',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='est_color',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='est_ibu_method',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
