# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0025_recipe_abv'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
