# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0027_auto_20170314_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='age',
            field=models.DecimalField(decimal_places=4, default=30.0, max_digits=10),
            preserve_default=False,
        ),
    ]
