# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0028_auto_20170314_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='taste_rating',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
