# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0029_auto_20170314_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hop_usage',
            old_name='carophyllene',
            new_name='caryophyllene',
        ),
    ]
