# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0030_auto_20170315_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hop_usage',
            name='time',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
