# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0032_fermentable_potential'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc_usage',
            name='use',
            field=models.CharField(default='Boil', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fermentable',
            name='color',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fermentable',
            name='raw_yield',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
