# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0033_auto_20170320_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misc_usage',
            name='time',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
