# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0036_mash_step_water_grain_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mash_step',
            name='ramp_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
