# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0037_auto_20170404_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pre_boil_og',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbonation_temp',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='keg_priming_factor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='priming_sugar_equiv',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
