# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0038_auto_20170405_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='est_pre_boil_og',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
