# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0039_recipe_est_pre_boil_og'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='default_efficiency',
            field=models.DecimalField(decimal_places=4, default=0.72, max_digits=10),
        ),
        migrations.AddField(
            model_name='equipment',
            name='default_mash_efficiency',
            field=models.DecimalField(decimal_places=4, default=0.8, max_digits=10),
        ),
    ]
