# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0042_auto_20170406_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_water_vol',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
