# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0043_recipe_total_water_vol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hop',
            name='form',
        ),
        migrations.AddField(
            model_name='hop_usage',
            name='form',
            field=models.CharField(default='Pellet', max_length=100),
            preserve_default=False,
        ),
    ]
