# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0045_auto_20170407_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='boil_size',
            new_name='est_boil_size',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='calories',
            new_name='est_calories',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='total_water_vol',
            new_name='est_total_water_vol',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='fg',
            new_name='measured_fg',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='og',
            new_name='measured_og',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='abv',
        ),
        migrations.AddField(
            model_name='recipe',
            name='measured_abv',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measured_batch_size',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measured_calories',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measured_pre_boil_og',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measured_pre_boil_vol',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
