# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0046_auto_20170407_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pre_boil_og',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='pre_boil_vol',
        ),
    ]
