# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0047_auto_20170407_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='efficiency',
            new_name='measured_efficiency',
        ),
    ]
