# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0048_auto_20170407_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='est_boil_size',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
