# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0052_auto_20170407_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='est_attenuation',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measured_attenuation',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
