# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0053_auto_20170407_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mash_profile_usage',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='mash_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.Mash_profile_usage'),
        ),
    ]
