# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0054_auto_20170408_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='mash_profile_usage',
            name='sparge_volume',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
