# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0058_auto_20170412_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.CharField(default='Low', max_length=20),
        ),
    ]
