# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0059_alert_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
