# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0060_auto_20170417_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
