# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0061_sensor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='checkin_inteveral',
            field=models.IntegerField(default=5),
        ),
    ]
