# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0062_sensor_checkin_inteveral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='checkin_inteveral',
            new_name='checkin_interval',
        ),
    ]
