# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0065_auto_20170417_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notification_timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
