# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0066_alert_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hop_usage',
            name='ibu_component',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
